const alumnoSchema = {
  type: "object",
  properties: {
    id: {type: "string"},
    curp: { type: "string", minLength:18, maxLength:18 },
    nombre: { type: "string" },
    apellido_paterno: { type: "string" },
    apellido_materno: { type: "string" },
    fecha_de_nacimiento: { type: "string", format: "date" },
    tutor_nombre: { type: "string" },
    tutor_apellido_paterno: { type: "string" },
    tutor_apellido_materno: { type: "string" },
    tutor_correo: { type: "string" , format: "email"},
    tutor_num_telefono: { type: "string", minLength:10, maxLength:10 },
    num_telefono: { type: "string", minLength:10, maxLength:10 },
    estado: { type: "string" },
    ciudad: { type: "string" },
    colonia: { type: "string" },
    codigo_postal: { type: "string", minLength:5, maxLength:5 },
    escolaridad: { type: "string" },
    ultima_escuela: { type: "string" },
  },
  required: [
    "curp",
    "nombre",
    "apellido_paterno",
    "apellido_materno",
    "fecha_de_nacimiento",
    "tutor_nombre",
    "tutor_apellido_paterno",
    "tutor_apellido_materno",
    "tutor_correo",
    "tutor_num_telefono",
    "num_telefono",
    "estado",
    "ciudad",
    "colonia",
    "codigo_postal",
    "escolaridad",
    "ultima_escuela",
  ],
  additionalProperties: true,
  errorMessage: {
    type: "Debe ser un Objeto", // will not replace internal "type" error for the property "foo"
  },
};

module.exports = { alumnoSchema };
